name: up Shell

on:
  push:
    branches:
      - main
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: chmod
        run: |
        chmod +X script.sh
        
      - name: ./script.sh
        run: |
        sudo bash ./script.sh
