name: up Shell

on:
  push:
    branches:
      - main
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: ./script.sh
        run: |
          chmod +X script.sh
          bash ./script.sh
